### ISSUE TITLE
Code snippet no longer works since the merge

### ISSUE THREAD

**Issue by perrauda** [geovistory/design-system#83] opened 2023-08-09 11:44 UTC
Concerning the package-optimization branch https://github.com/geovistory/design-system/pull/70

Since the merge, the code snippet no longer works.

Example:
![image](https://github.com/geovistory/design-system/assets/5019779/fc52f3d8-df58-4b4d-9869-676a942e8cb3)

Commit: https://github.com/geovistory/design-system/commit/fe87cebdb91b38d5478c757f1a78ce321d7c6df7

The changes in tsxToHTML.ts may be the cause, _returnvalue_ remains undefined because format(...) is asynchronous and returns the value too late.

```js
let returnvalue: string;
  format(htmlString, { plugins: [pluginXML], parser: 'xml', singleQuote: true, singleAttributePerLine: true }).then(v => {
    returnvalue = v.replace(/&frasl;/g, '/').replace(/&lt;/g, '<');
  });
  return returnvalue;
```

**Comment by flicksolutions** [comment] 2023-08-15 12:12
@perrauda can't reproduce.
On the main branch I get the full code displayed?
![grafik](https://github.com/geovistory/design-system/assets/33655122/7d0a2383-fcf4-4e47-a626-f96408bfd61c)

**Comment by flicksolutions** [comment] 2023-08-15 15:27
@perrauda should be solved...

by the way - general remark about our workflow: I misunderstood you, when you told be about the bug. #70 wasn't yet merged into main! Therefore no new issue should've been raised but you could've directly review #70 and tell me about the bug right there. This would've been a better aproach I think.

**Comment by perrauda** [comment] 2023-09-21 12:49
@flicksolutions @joschne this ticket is solved, isn't it?

**Comment by flicksolutions** [comment] 2023-09-22 16:14
Yes, definitely! Thanks for the heads up!

**Closed by flicksolutions** 2023-09-22 16:14 UTC
Labels: bug
